### PR TITLE
Fixes the app service documentation link on the main page.

### PR DESCRIPTION
**Pull request by AndreasKl**
The link was pointing to an non existing page causing a 404.

## Checklist

* [x] Tests written for all new code
* [x] Linter has been satisfied
* [x] Sign-off given on the changes (see CONTRIBUTING.md)

### CODE REVIEW

**Review by turt2live — CHANGES_REQUESTED** [review]
The underscore isn't supposed to be there. A fix to the documentation to avoid generating such a link would be appreciated.

**Comment by AndreasKl** [comment]
Ok, I'll have a look if jsdocs or the github action is causing this.

**Comment by AndreasKl** [comment]
As far as I understand jsdocs thinks there will be a clash with `Appservice.html` therefore adding the underscore even if the tutorial prefix is added.

Is renaming an OKish workaround?

**Comment by turt2live** [comment]
renaming also isn't ideal. Is there an upstream issue for this?

**Comment by AndreasKl** [comment]
Sorry, I currently do not have time to dig deeper into jsdoc.

**Pull request closed without merging**
