### PR TITLE
Warning Message for Newbies

### PR DESCRIPTION
**Pull request by SomnathDas**

### CODE REVIEW

**Comment by turt2live** [comment]
it will work in encrypted rooms if the author sets things up correctly.

**Comment by SomnathDas** [comment]
> it will work in encrypted rooms if the author sets things up correctly.

Wow !!!
Can you guide me 🌞✨ how

**Comment by turt2live** [comment]
Use a [PantalaimonClient](https://turt2live.github.io/matrix-bot-sdk/PantalaimonClient.html) with [Pantalaimon](https://github.com/matrix-org/pantalaimon/) (docker image works best for bots)

**Comment by SomnathDas** [comment]
@turt2live Can we send media files using matrix-bot-sdk ?

**Comment by turt2live** [comment]
Yes, you upload the media first then use the returned ID in your message event.

I suggest joining https://matrix.to/#/#matrix-bot-sdk:t2bot.io for help and support, as this is not the right place.

**Comment by SomnathDas** [comment]
@turt2live  Thanks pal!!!!

**Pull request closed without merging**
